### ISSUE TITLE
The color isn't changing based on album color 

### ISSUE THREAD

**Issue by alfredoxyanez** [sekaru/spotify-lifx-visualiser#1]
I run the app by :
npm start --beatmode 1  --colourmode 2

The color of my light strip does not change. It stays an orange color. Not based on the album color at all. Moreover it also doesn't cycle through the color wheel. It stays the same color but changes the brightness.

**Comment by tudddorrr** [comment]
What OS are you on?

**Comment by alfredoxyanez** [comment]
MacOS 10.13

**Comment by tudddorrr** [comment]
Oh I see the issue, you should be doing "npm start -- --beatmode 1 --colourmode 2". Its to do with the way npm handles arguments you need to put "--" between the command and the arguments you want to pass.

**Comment by alfredoxyanez** [comment]
That did it! thanks!

**Comment by alfredoxyanez** [comment]
Might be beneficial to put that in the readme.

**Comment by tudddorrr** [comment]
Shall do yeah
