### ISSUE TITLE
how to login with lifx?

### ISSUE THREAD

**Issue by tchopra17** [sekaru/spotify-lifx-visualiser#5]

**Comment by tudddorrr** [comment]
What do you mean by logging in with lifx?

**Comment by tchopra17** [comment]
like when I run npm start it logins into spotify fine, but lights aren't doing anything.

**Comment by tudddorrr** [comment]
Are your lights on and at a decent brightness? The app doesn't turn them on or make them bright. Also there's a few fixes in the latest commits you may want to pull down (although I don't think this is related to your issue)

**Comment by tchopra17** [comment]
Yes the lights are on and on full brightness. Does it automatically connect to them based on the network? The lights are running on a wifi network broadcasted by my laptop since my college wifi doesn’t allow for device control.

**Comment by tudddorrr** [comment]
Yeah that sounds like your issue. They have to be on the same network as your laptop.

**Comment by tchopra17** [comment]
The lights are now on the same network as my laptop but they are still not responding.

**Comment by tudddorrr** [comment]
Can you show me your console output?

**Comment by tchopra17** [comment]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT dn.js.1
(index):6  Uncaught ReferenceError: gbar is not defined
    at onload ((index):6)
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT ui:1

**Comment by tudddorrr** [comment]
Looks like your network is blocking the connection. Either your college's wifi has a firewall or (from some quick googling) maybe an adblocker (but the firewall is more likely).
